export declare const messages: any;
export declare const useStrings: () => {
    delegateToDRep: any;
    delegatingToDRep: any;
    designatingSomeoneElse: any;
    governanceStatus: any;
    governanceStatusInfo: any;
    abstain: any;
    abstainInfo: any;
    noConfidence: any;
    noConfidenceInfo: any;
    learnMore: any;
    becomeADrep: any;
    drepId: any;
    registerGovernance: any;
    reviewSelection: any;
    statusSelected: (status: any) => any;
    chooseDrep: any;
    designatedSomeone: any;
    transactionDetails: any;
    operations: any;
    selectAbstein: any;
    selectNoConfidence: any;
    back: any;
    confirm: any;
    total: any;
    password: any;
    wrongPassword: any;
    identifyDrep: any;
    incorectFormat: any;
    statusPending: any;
    thanksForParticipation: any;
    theTransactionCanTake: any;
    participatingInGovernance: any;
    goToGovernance: any;
};
